package com.example.musicapplication.ui.home;

import android.content.Context;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import com.example.musicapplication.MainActivity;
import com.example.musicapplication.R;
import com.example.musicapplication.model.Song;
import com.example.musicapplication.ui.library.LibraryFragment;
import com.example.musicapplication.ui.playing.SongPlayingFragment;

import java.util.ArrayList;
import java.util.List;

public class ItemSongAdapter extends RecyclerView.Adapter<ItemSongAdapter.ItemHolder> {
    private static final String TAG = "Item Adapter";
    private Context mContext;
    private List<Song> songList = new ArrayList<>();

    public ItemSongAdapter(Context mContext){
        this.mContext = mContext;
    }

    @NonNull
    @Override
    public ItemSongAdapter.ItemHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_song_playlist, parent,false);
        return new ItemHolder(v);
    }

    @Override
    public void onBindViewHolder(@NonNull ItemSongAdapter.ItemHolder itemHolder, int i) {
        // get item song ith
        //final Song songItem = songList.get(i);
        // tên tương ứng     itemHolder.title.setText(playlist.name);

        // get uri of art
        Log.d(TAG, "position: " + i);

//        new PlaylistBitmapLoader(this,playlist,itemHolder).execute();
//
//        itemHolder.art.setTag(firstAlbumID);
//        itemHolder.title.setText(playlist.name);
//        if(Util.isLollipop()) itemHolder.art.setTransitionName("transition_album_art"+i);

        ImageView mSongImage = itemHolder.art;
        mSongImage.setImageResource( R.drawable.default_image_round);
        TextView mMusicName = itemHolder.title;
        mMusicName.setText( "a Quan dep trai ok?" );
        TextView mAuthor = itemHolder.author;
        mAuthor.setText( "Quan Nguyen" );

    }

    @Override
    public int getItemCount() {
        return 7;
    }

    public class ItemHolder extends RecyclerView.ViewHolder implements View.OnClickListener{
        protected TextView title;
        protected TextView author;
        protected ImageView art;
        View view_over;
        protected View root;
        MainActivity main = (MainActivity) mContext;

        public ItemHolder(@NonNull View itemView) {
            super( itemView );
            root = itemView;
            this.title = itemView.findViewById( R.id.musicName);
            this.author = itemView.findViewById(R.id.author);
            this.art = itemView.findViewById(R.id.song_image);
            view_over = itemView.findViewById(R.id.song_over);
            view_over.setOnClickListener(this);
            //view_over.setOnTouchListener(this);
        }

        @Override
        public void onClick(View v) {
            Log.d(TAG, "song click----------------");
            main.goToFragment( SongPlayingFragment.newInstance());
        }
    }

//    private static class PlaylistBitmapLoader extends AsyncTask<Void,Void, Bitmap> {
//        private ItemSongAdapter mAdapter;
//        private ItemHolder mItemHolder;
//        private Song mSong;
//
//        PlaylistBitmapLoader(ItemSongAdapter adapter, Song playlist, ItemHolder item) {
//            mAdapter = adapter;
//            mItemHolder = item;
//            mSong = playlist;
//        }
//        @Override
//        protected void onPostExecute(Bitmap bitmap) {
//            mItemHolder.art.setImageBitmap(bitmap);
//        }
//
//        @Override
//        protected Bitmap doInBackground(Void... v) {
//
//            List<Song> l = mAdapter.getPlaylistWithListId(mItemHolder.getAdapterPosition(),mPlaylist.id);
//            return AutoGeneratedPlaylistBitmap.getBitmap(mAdapter.mContext,l,false,false);
//        }
//    }
}
